<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <RootNamespace>lab1</RootNamespace>
    <AssemblyName>lab1</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\lab1.Core\lab1.Core.csproj" />
  </ItemGroup>

</Project>
