<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ImageInspector</RootNamespace>
<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AssemblyName>ImageInspector</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="WpfAnimatedGif" Version="2.0.2" />
    <PackageReference Include="XamlAnimatedGif" Version="2.3.2" />
  </ItemGroup>
</Project>
